name: petli_assignment
description: Assignment for petli

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core
  intl: ^0.17.0
  logging: ^1.0.1

  # architecture
  get_it: ^7.2.0
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  either_option: ^2.0.0

  # networking
  dio: ^4.0.1
  dio_logger: ^4.0.8+8

  # code generation
  json_annotation: ^4.0.1
  freezed_annotation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generation
  build_runner: ^2.0.3
  json_serializable: ^6.1.1
  freezed: ^1.0.2+1

  # tests
  mocktail: ^0.2.0
  bloc_test: ^9.0.1

  # quality
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/